apiVersion: {{ template "service.apiVersion" .}}
kind: Service
metadata:
   name: {{ .Release.Name}}
   namespace: {{ .Values.namespace }}
   {{- template "usersdeps.labels" . }}
spec:
  clusterIP: None
  selector:
    app: {{ .Release.Name}}
  ports:
    {{- range $key, $value := .Values.serviceports }}
    - protocol: {{ $value.protocol }}
      port: {{ $value.port }}
      targetPort: {{ $value.targetPort }}
    {{- end }}